import type { Car } from "../types/car";

export const mockCars: Car[] = [
    {
        id: "1",
        name: "Model S",
        brand: "Tesla",
        category: "Luxury",
        pricePerDay: 129,
        imageUrl:
            "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.9,
        locations: [],
        description:
            "Experience the pinnacle of electric luxury. The Tesla Model S combines breathtaking performance with a refined interior and cutting-edge technology.",
        features: [
            "Autopilot",
            "17-inch Touchscreen",
            "Premium Audio",
            "All-Wheel Drive",
            "Heated Seats",
            "Navigation",
        ],
    },
    {
        id: "2",
        name: "Range Rover Sport",
        brand: "Land Rover",
        category: "SUV",
        pricePerDay: 149,
        imageUrl:
            "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        year: 2023,
        rating: 4.8,
        locations: [],
        description:
            "Commanding presence meets refined capability. The Range Rover Sport delivers luxury and off-road performance in equal measure.",
        features: [
            "Terrain Management",
            "Panoramic Roof",
            "Meridian Audio",
            "Heated/Cooled Seats",
            "Air Suspension",
            "Navigation",
        ],
    },
    {
        id: "3",
        name: "Mustang GT",
        brand: "Ford",
        category: "Convertible",
        pricePerDay: 99,
        imageUrl:
            "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=800&q=80",
        seats: 4,
        transmission: "Manual",
        fuelType: "Petrol",
        year: 2022,
        rating: 4.7,
        locations: [],
        description:
            "An American icon reborn. The Mustang GT delivers raw, exhilarating performance with a roaring V8 engine and classic muscle car styling.",
        features: [
            "V8 Engine",
            "Convertible Roof",
            "Sport Seats",
            "SYNC Infotainment",
            "Brembo Brakes",
            "Launch Control",
        ],
    },
    {
        id: "4",
        name: "Civic",
        brand: "Honda",
        category: "Economy",
        pricePerDay: 49,
        imageUrl:
            "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.6,
        locations: [],
        description:
            "Smart, efficient, and reliable. The Honda Civic is the perfect city companion offering great fuel economy and a comfortable ride.",
        features: [
            "Apple CarPlay",
            "Android Auto",
            "Lane Keep Assist",
            "Adaptive Cruise Control",
            "Rear Camera",
            "Fuel Efficient",
        ],
    },
    {
        id: "5",
        name: "3 Series",
        brand: "BMW",
        category: "Sedan",
        pricePerDay: 109,
        imageUrl:
            "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.8,
        locations: [],
        description:
            "The benchmark sports sedan. The BMW 3 Series offers the perfect balance of dynamic driving pleasure and everyday practicality.",
        features: [
            "iDrive System",
            "Ambient Lighting",
            "Harman Kardon Audio",
            "Sport Mode",
            "Parking Sensors",
            "Wireless Charging",
        ],
    },
    {
        id: "6",
        name: "GLE 450",
        brand: "Mercedes-Benz",
        category: "SUV",
        pricePerDay: 159,
        imageUrl:
            "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
        seats: 7,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.9,
        locations: [],
        description:
            "Luxury without compromise. The Mercedes-Benz GLE 450 redefines what a premium SUV can be with its opulent interior and smooth hybrid powertrain.",
        features: [
            "MBUX Infotainment",
            "Burmester Audio",
            "Air Body Control",
            "7 Seats",
            "360 Camera",
            "Massage Seats",
        ],
    },
    {
        id: "7",
        name: "Camry",
        brand: "Toyota",
        category: "Sedan",
        pricePerDay: 59,
        imageUrl:
            "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.5,
        locations: [],
        description:
            "Comfort, reliability, and efficiency rolled into one. The Toyota Camry Hybrid is a proven choice for business or leisure travel.",
        features: [
            "Toyota Safety Sense",
            "Apple CarPlay",
            "Dual-Zone Climate",
            "Heated Front Seats",
            "Pre-Collision System",
            "Blind Spot Monitor",
        ],
    },
    {
        id: "8",
        name: "911 Carrera",
        brand: "Porsche",
        category: "Luxury",
        pricePerDay: 249,
        imageUrl:
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
        seats: 2,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 5.0,
        locations: [],
        description:
            "A legend in every sense. The Porsche 911 Carrera delivers an unmatched driving experience with iconic styling and extraordinary performance.",
        features: [
            "Sport Chrono Package",
            "Bose Audio",
            "Sport Exhaust",
            "PASM Suspension",
            "Rear-Wheel Steering",
            "Night Vision",
        ],
    },
];