import dotenv from "dotenv";
import mongoose from "mongoose";
import Vehicle from "../models/Vehicle";

dotenv.config();

const vehicles = [
    {
        name: "Model S",
        brand: "Tesla",
        category: "Luxury",
        pricePerDay: 129,
        imageUrl: "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.9,
        locations: ["New York", "Los Angeles", "Miami"],
        description: "Experience the pinnacle of electric luxury. The Tesla Model S combines breathtaking performance with a refined interior and cutting-edge technology.",
        features: ["Autopilot", "17-inch Touchscreen", "Premium Audio", "All-Wheel Drive", "Heated Seats", "Navigation"],
    },
    {
        name: "Model 3",
        brand: "Tesla",
        category: "Sedan",
        pricePerDay: 89,
        imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.7,
        locations: ["Los Angeles", "San Francisco", "Las Vegas"],
        description: "The Tesla Model 3 is the world's best-selling electric car, combining efficiency, performance, and cutting-edge technology in a sleek sedan package.",
        features: ["Autopilot", "15-inch Touchscreen", "Over-the-Air Updates", "All-Wheel Drive", "Glass Roof", "Navigation"],
    },
    {
        name: "Range Rover Sport",
        brand: "Land Rover",
        category: "SUV",
        pricePerDay: 149,
        imageUrl: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Diesel",
        year: 2023,
        rating: 4.8,
        locations: ["New York", "Chicago", "Boston"],
        description: "Commanding presence meets refined capability. The Range Rover Sport delivers luxury and off-road performance in equal measure.",
        features: ["Terrain Management", "Panoramic Roof", "Meridian Audio", "Heated/Cooled Seats", "Air Suspension", "Navigation"],
    },
    {
        name: "Defender 110",
        brand: "Land Rover",
        category: "SUV",
        pricePerDay: 139,
        imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80",
        seats: 7,
        transmission: "Automatic",
        fuelType: "Diesel",
        year: 2023,
        rating: 4.7,
        locations: ["Houston", "Chicago", "Las Vegas"],
        description: "The iconic Land Rover Defender 110 is built for adventure. With seating for seven and legendary off-road capability, it goes anywhere in style.",
        features: ["Terrain Response", "Wade Sensing", "ClearSight Mirror", "7 Seats", "Pivi Pro Infotainment", "Air Suspension"],
    },
    {
        name: "Mustang GT",
        brand: "Ford",
        category: "Convertible",
        pricePerDay: 99,
        imageUrl: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=800&q=80",
        seats: 4,
        transmission: "Manual",
        fuelType: "Petrol",
        year: 2022,
        rating: 4.7,
        locations: ["Miami", "Las Vegas", "Los Angeles"],
        description: "An American icon reborn. The Mustang GT delivers raw, exhilarating performance with a roaring V8 engine and classic muscle car styling.",
        features: ["V8 Engine", "Convertible Roof", "Sport Seats", "SYNC Infotainment", "Brembo Brakes", "Launch Control"],
    },
    {
        name: "F-150 Raptor",
        brand: "Ford",
        category: "SUV",
        pricePerDay: 119,
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.6,
        locations: ["Houston", "Las Vegas", "Chicago"],
        description: "The Ford F-150 Raptor is the ultimate high-performance off-road pickup truck, combining brute strength with surprising refinement.",
        features: ["Fox Racing Shocks", "37-inch Tires", "SYNC 4", "360 Camera", "Trail Control", "Recaro Seats"],
    },
    {
        name: "Civic",
        brand: "Honda",
        category: "Economy",
        pricePerDay: 49,
        imageUrl: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.6,
        locations: ["New York", "Boston", "Chicago"],
        description: "Smart, efficient, and reliable. The Honda Civic is the perfect city companion offering great fuel economy and a comfortable ride.",
        features: ["Apple CarPlay", "Android Auto", "Lane Keep Assist", "Adaptive Cruise Control", "Rear Camera", "Fuel Efficient"],
    },
    {
        name: "CR-V",
        brand: "Honda",
        category: "SUV",
        pricePerDay: 69,
        imageUrl: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.5,
        locations: ["San Francisco", "Los Angeles", "Boston"],
        description: "The Honda CR-V Hybrid offers the perfect blend of practicality and efficiency, with generous cargo space and a comfortable ride for any journey.",
        features: ["Honda Sensing", "Apple CarPlay", "Heated Seats", "Power Tailgate", "Dual-Zone Climate", "Hybrid Engine"],
    },
    {
        name: "3 Series",
        brand: "BMW",
        category: "Sedan",
        pricePerDay: 109,
        imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.8,
        locations: ["New York", "Miami", "Boston"],
        description: "The benchmark sports sedan. The BMW 3 Series offers the perfect balance of dynamic driving pleasure and everyday practicality.",
        features: ["iDrive System", "Ambient Lighting", "Harman Kardon Audio", "Sport Mode", "Parking Sensors", "Wireless Charging"],
    },
    {
        name: "X5",
        brand: "BMW",
        category: "SUV",
        pricePerDay: 139,
        imageUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.8,
        locations: ["Chicago", "New York", "San Francisco"],
        description: "The BMW X5 sets the standard for luxury SUVs with its powerful performance, sophisticated interior, and cutting-edge technology.",
        features: ["Live Cockpit Professional", "Panoramic Roof", "Harman Kardon Audio", "Gesture Control", "Parking Assistant", "Heated Seats"],
    },
    {
        name: "M4 Competition",
        brand: "BMW",
        category: "Convertible",
        pricePerDay: 189,
        imageUrl: "https://images.unsplash.com/photo-1617654112368-307921291f42?w=800&q=80",
        seats: 4,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.9,
        locations: ["Miami", "Los Angeles", "Las Vegas"],
        description: "The BMW M4 Competition Convertible delivers exhilarating open-top performance with a twin-turbocharged inline-six engine and race-inspired dynamics.",
        features: ["M xDrive", "Carbon Fibre Roof", "M Sport Exhaust", "Launch Control", "Adaptive M Suspension", "Harman Kardon Audio"],
    },
    {
        name: "GLE 450",
        brand: "Mercedes-Benz",
        category: "SUV",
        pricePerDay: 159,
        imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
        seats: 7,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.9,
        locations: ["New York", "Los Angeles", "Miami"],
        description: "Luxury without compromise. The Mercedes-Benz GLE 450 redefines what a premium SUV can be with its opulent interior and smooth hybrid powertrain.",
        features: ["MBUX Infotainment", "Burmester Audio", "Air Body Control", "7 Seats", "360 Camera", "Massage Seats"],
    },
    {
        name: "C-Class",
        brand: "Mercedes-Benz",
        category: "Sedan",
        pricePerDay: 99,
        imageUrl: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.7,
        locations: ["Boston", "Chicago", "Houston"],
        description: "The Mercedes-Benz C-Class perfectly blends sport and luxury, offering a refined driving experience with state-of-the-art technology in a compact package.",
        features: ["MBUX System", "64-Color Ambient Lighting", "Burmester Audio", "Heated Seats", "Digital Instrument Cluster", "Wireless Charging"],
    },
    {
        name: "E-Class",
        brand: "Mercedes-Benz",
        category: "Sedan",
        pricePerDay: 119,
        imageUrl: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.8,
        locations: ["New York", "San Francisco", "Las Vegas"],
        description: "The Mercedes-Benz E-Class represents the ideal combination of luxury, technology, and comfort in the executive sedan segment.",
        features: ["MBUX Hyperscreen", "Burmester 3D Audio", "Air Suspension", "Driving Assistance Package", "Massage Seats", "Head-Up Display"],
    },
    {
        name: "AMG GT",
        brand: "Mercedes-Benz",
        category: "Convertible",
        pricePerDay: 229,
        imageUrl: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80",
        seats: 2,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.9,
        locations: ["Miami", "Las Vegas", "Los Angeles"],
        description: "The Mercedes-AMG GT Roadster is a pure sports car experience with a handcrafted AMG engine, stunning design, and exhilarating open-top performance.",
        features: ["AMG Performance Exhaust", "Carbon Fibre Package", "AMG Track Pace", "Burmester Audio", "AMG Ride Control", "Launch Control"],
    },
    {
        name: "911 Carrera",
        brand: "Porsche",
        category: "Luxury",
        pricePerDay: 249,
        imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
        seats: 2,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 5.0,
        locations: ["Los Angeles", "Miami", "Las Vegas"],
        description: "A legend in every sense. The Porsche 911 Carrera delivers an unmatched driving experience with iconic styling and extraordinary performance.",
        features: ["Sport Chrono Package", "Bose Audio", "Sport Exhaust", "PASM Suspension", "Rear-Wheel Steering", "Night Vision"],
    },
    {
        name: "Cayenne",
        brand: "Porsche",
        category: "SUV",
        pricePerDay: 179,
        imageUrl: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.8,
        locations: ["New York", "San Francisco", "Chicago"],
        description: "The Porsche Cayenne combines the performance of a sports car with the versatility of an SUV, setting the benchmark in its class.",
        features: ["Porsche Communication Management", "Bose Surround Sound", "Air Suspension", "Sport Chrono", "360 Camera", "Panoramic Roof"],
    },
    {
        name: "Panamera",
        brand: "Porsche",
        category: "Luxury",
        pricePerDay: 219,
        imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
        seats: 4,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.9,
        locations: ["New York", "Los Angeles", "Boston"],
        description: "The Porsche Panamera redefines the luxury sports sedan with stunning performance, innovative technology, and exceptional comfort.",
        features: ["4-Zone Climate", "Burmester High-End Audio", "Rear Entertainment", "Night Vision", "Sport Chrono", "Air Suspension"],
    },
    {
        name: "Camry",
        brand: "Toyota",
        category: "Sedan",
        pricePerDay: 59,
        imageUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.5,
        locations: ["Houston", "Chicago", "Boston"],
        description: "Comfort, reliability, and efficiency rolled into one. The Toyota Camry Hybrid is a proven choice for business or leisure travel.",
        features: ["Toyota Safety Sense", "Apple CarPlay", "Dual-Zone Climate", "Heated Front Seats", "Pre-Collision System", "Blind Spot Monitor"],
    },
    {
        name: "RAV4",
        brand: "Toyota",
        category: "SUV",
        pricePerDay: 69,
        imageUrl: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.6,
        locations: ["Houston", "San Francisco", "Boston"],
        description: "The Toyota RAV4 Hybrid is America's best-selling SUV combining practicality, efficiency, and all-weather capability.",
        features: ["Toyota Safety Sense", "Apple CarPlay", "All-Wheel Drive", "Power Tailgate", "Heated Seats", "Panoramic Moonroof"],
    },
    {
        name: "GR Supra",
        brand: "Toyota",
        category: "Convertible",
        pricePerDay: 119,
        imageUrl: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80",
        seats: 2,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.8,
        locations: ["Los Angeles", "Miami", "Las Vegas"],
        description: "The Toyota GR Supra is a legendary sports car reborn, offering thrilling performance with a turbocharged inline-six engine.",
        features: ["Sport Exhaust", "Adaptive Variable Suspension", "JBL Audio", "Head-Up Display", "Launch Control", "Digital Cockpit"],
    },
    {
        name: "Giulia",
        brand: "Alfa Romeo",
        category: "Sedan",
        pricePerDay: 109,
        imageUrl: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.6,
        locations: ["New York", "Miami", "Boston"],
        description: "The Alfa Romeo Giulia combines Italian passion with precision engineering, delivering a driving experience that is both emotional and exhilarating.",
        features: ["Alfa DNA Pro", "Harman Kardon Audio", "Carbon Fibre Trim", "Active Aero", "Sport Seats", "8.8-inch Infotainment"],
    },
    {
        name: "Stelvio",
        brand: "Alfa Romeo",
        category: "SUV",
        pricePerDay: 119,
        imageUrl: "https://images.unsplash.com/photo-1547744152-14d985cb937f?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.5,
        locations: ["Chicago", "Houston", "New York"],
        description: "The Alfa Romeo Stelvio is the most driver-focused SUV in its class, with stunning Italian design and exhilarating performance.",
        features: ["Alfa DNA Pro", "Harman Kardon Audio", "Q4 All-Wheel Drive", "Carbon Fibre Package", "Sport Seats", "Panoramic Roof"],
    },
    {
        name: "Mustang Mach-E",
        brand: "Ford",
        category: "SUV",
        pricePerDay: 89,
        imageUrl: "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.5,
        locations: ["San Francisco", "Los Angeles", "New York"],
        description: "The Ford Mustang Mach-E brings the iconic Mustang spirit into the electric age with thrilling performance and impressive range.",
        features: ["SYNC 4A", "15.5-inch Touchscreen", "Ford Co-Pilot360", "Over-the-Air Updates", "Panoramic Roof", "B&O Sound System"],
    },
    {
        name: "Ioniq 6",
        brand: "Hyundai",
        category: "Sedan",
        pricePerDay: 79,
        imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.6,
        locations: ["San Francisco", "Los Angeles", "Seattle"],
        description: "The Hyundai IONIQ 6 is a revolutionary electric sedan with an aerodynamic design, ultra-fast charging, and an impressive range of up to 361 miles.",
        features: ["800V Ultra-Fast Charging", "Digital Side Mirrors", "Relaxation Seats", "Augmented Reality HUD", "Over-the-Air Updates", "Vehicle-to-Load"],
    },
    {
        name: "Tucson",
        brand: "Hyundai",
        category: "SUV",
        pricePerDay: 65,
        imageUrl: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.5,
        locations: ["Houston", "Chicago", "Boston"],
        description: "The Hyundai Tucson Hybrid combines bold design with hybrid efficiency, offering a spacious and feature-rich interior for every journey.",
        features: ["10.25-inch Touchscreen", "Bose Premium Audio", "Blind-View Monitor", "Heated/Ventilated Seats", "Remote Smart Parking", "Panoramic Roof"],
    },
    {
        name: "EV6",
        brand: "Kia",
        category: "SUV",
        pricePerDay: 85,
        imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.7,
        locations: ["Los Angeles", "San Francisco", "New York"],
        description: "The Kia EV6 is a groundbreaking electric crossover that charges from 10-80% in just 18 minutes and delivers exhilarating performance.",
        features: ["800V Ultra-Fast Charging", "Meridian Audio", "Augmented Reality HUD", "Vehicle-to-Load", "Panoramic Roof", "Remote Smart Parking"],
    },
    {
        name: "Sportage",
        brand: "Kia",
        category: "SUV",
        pricePerDay: 62,
        imageUrl: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.4,
        locations: ["Houston", "Chicago", "Miami"],
        description: "The Kia Sportage Hybrid is a stylish and practical SUV with a bold design, spacious interior, and impressive fuel efficiency.",
        features: ["10.25-inch Dual Curved Display", "Bose Premium Audio", "Heated/Ventilated Seats", "Blind-Spot Collision Warning", "Panoramic Roof", "Smart Power Tailgate"],
    },
    {
        name: "Giulia Quadrifoglio",
        brand: "Alfa Romeo",
        category: "Luxury",
        pricePerDay: 199,
        imageUrl: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.9,
        locations: ["New York", "Miami", "Los Angeles"],
        description: "The Alfa Romeo Giulia Quadrifoglio is a true super sedan, with a Ferrari-derived V6 engine producing 505 horsepower for breathtaking performance.",
        features: ["Ferrari-Derived V6", "Carbon Ceramic Brakes", "Akrapovic Exhaust", "Carbon Fibre Package", "Sabelt Racing Seats", "Active Aero"],
    },
    {
        name: "Wrangler",
        brand: "Jeep",
        category: "SUV",
        pricePerDay: 89,
        imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.6,
        locations: ["Las Vegas", "Houston", "Los Angeles"],
        description: "The Jeep Wrangler is the ultimate off-road icon, with removable doors and roof, making every adventure unforgettable.",
        features: ["Rock-Trac 4x4", "Removable Doors & Roof", "Uconnect 5", "Trail Rated Badge", "Skid Plates", "Locking Differentials"],
    },
    {
        name: "Grand Cherokee",
        brand: "Jeep",
        category: "SUV",
        pricePerDay: 99,
        imageUrl: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.6,
        locations: ["Chicago", "Houston", "New York"],
        description: "The Jeep Grand Cherokee 4xe combines legendary off-road capability with plug-in hybrid efficiency for the ultimate premium SUV experience.",
        features: ["Quadra-Lift Air Suspension", "McIntosh Audio", "Uconnect 5", "Selec-Terrain", "Night Vision", "Panoramic Roof"],
    },
    {
        name: "Urus",
        brand: "Lamborghini",
        category: "SUV",
        pricePerDay: 399,
        imageUrl: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 5.0,
        locations: ["Miami", "Los Angeles", "Las Vegas"],
        description: "The Lamborghini Urus is the world's first Super Sport Utility Vehicle, combining the soul of a super sports car with the versatility of an SUV.",
        features: ["Twin-Turbo V8", "ANIMA Selector", "Bang & Olufsen Audio", "Carbon Ceramic Brakes", "Laser Headlights", "Alcantara Interior"],
    },
    {
        name: "Huracán",
        brand: "Lamborghini",
        category: "Convertible",
        pricePerDay: 499,
        imageUrl: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
        seats: 2,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 5.0,
        locations: ["Miami", "Las Vegas", "Los Angeles"],
        description: "The Lamborghini Huracán Spyder is a mid-engine masterpiece that delivers a naturally aspirated V10 soundtrack under the open sky.",
        features: ["V10 Naturally Aspirated", "LDVI System", "Carbon Ceramic Brakes", "Sensonum Audio", "Electrochromic Roof", "Forged Composite Interior"],
    },
    {
        name: "SF90 Stradale",
        brand: "Ferrari",
        category: "Luxury",
        pricePerDay: 599,
        imageUrl: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80",
        seats: 2,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 5.0,
        locations: ["Miami", "Los Angeles", "Las Vegas"],
        description: "The Ferrari SF90 Stradale is Ferrari's most powerful road car ever, a plug-in hybrid with 986 horsepower and breathtaking performance.",
        features: ["986 HP Hybrid", "eManettino", "Head-Up Display", "Carbon Fibre Body", "Side Slip Control", "Ferrari Dynamic Enhancer"],
    },
    {
        name: "Roma",
        brand: "Ferrari",
        category: "Luxury",
        pricePerDay: 449,
        imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
        seats: 2,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.9,
        locations: ["New York", "Miami", "Los Angeles"],
        description: "The Ferrari Roma embodies la dolce vita with its elegant design, twin-turbocharged V8 engine, and grand touring character.",
        features: ["Twin-Turbo V8", "Dual Cockpit Interior", "Ferrari Telemetry", "Carbon Ceramic Brakes", "JBL Audio", "Manettino Dial"],
    },
    {
        name: "Phantom",
        brand: "Rolls-Royce",
        category: "Luxury",
        pricePerDay: 799,
        imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 5.0,
        locations: ["New York", "Los Angeles", "Miami"],
        description: "The Rolls-Royce Phantom is the pinnacle of automotive luxury, handcrafted to perfection with bespoke interiors and a whisper-quiet ride.",
        features: ["Starlight Headliner", "Gallery Dashboard", "Self-Closing Doors", "Magic Carpet Ride", "Bespoke Audio", "Night Vision"],
    },
    {
        name: "Cullinan",
        brand: "Rolls-Royce",
        category: "SUV",
        pricePerDay: 699,
        imageUrl: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 5.0,
        locations: ["New York", "Los Angeles", "Las Vegas"],
        description: "The Rolls-Royce Cullinan is the most luxurious SUV ever created, offering effortless everywhere capability with uncompromising opulence.",
        features: ["Starlight Headliner", "Viewing Suite", "Self-Closing Doors", "Magic Carpet Ride", "Bespoke Audio", "Night Vision"],
    },
    {
        name: "Continental GT",
        brand: "Bentley",
        category: "Luxury",
        pricePerDay: 349,
        imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
        seats: 4,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.9,
        locations: ["New York", "Miami", "Los Angeles"],
        description: "The Bentley Continental GT is the definitive grand tourer, combining handcrafted luxury with breathtaking W12 performance.",
        features: ["W12 Engine", "Rotating Display", "Naim Audio", "Air Suspension", "Night Vision", "Massage Seats"],
    },
    {
        name: "Bentayga",
        brand: "Bentley",
        category: "SUV",
        pricePerDay: 299,
        imageUrl: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.9,
        locations: ["New York", "Chicago", "Los Angeles"],
        description: "The Bentley Bentayga Hybrid is the world's most luxurious SUV, combining plug-in hybrid efficiency with handcrafted Bentley opulence.",
        features: ["Plug-In Hybrid", "Naim Audio", "Air Suspension", "Night Vision", "Massage Seats", "Bentley Dynamic Ride"],
    },
    {
        name: "Taycan",
        brand: "Porsche",
        category: "Luxury",
        pricePerDay: 269,
        imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        seats: 4,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.9,
        locations: ["San Francisco", "Los Angeles", "New York"],
        description: "The Porsche Taycan is the world's most exciting electric sports car, combining zero emissions with extraordinary Porsche performance.",
        features: ["800V Architecture", "Burmester 3D Audio", "AR Head-Up Display", "Air Suspension", "Sport Chrono", "Over-the-Air Updates"],
    },
    {
        name: "Model X",
        brand: "Tesla",
        category: "SUV",
        pricePerDay: 149,
        imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80",
        seats: 7,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.8,
        locations: ["San Francisco", "Los Angeles", "New York"],
        description: "The Tesla Model X is a premium electric SUV with distinctive falcon-wing doors, seating for seven, and unmatched electric performance.",
        features: ["Falcon Wing Doors", "17-inch Touchscreen", "Autopilot", "7 Seats", "HEPA Air Filter", "Bioweapon Defense Mode"],
    },
    {
        name: "i4",
        brand: "BMW",
        category: "Sedan",
        pricePerDay: 99,
        imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.7,
        locations: ["San Francisco", "Chicago", "Boston"],
        description: "The BMW i4 is a fully electric gran coupe that delivers thrilling M Performance with zero emissions and a stunning 300-mile range.",
        features: ["Curved Display", "Harman Kardon Audio", "Active Driving Assistant", "Wireless Charging", "Panoramic Roof", "Over-the-Air Updates"],
    },
    {
        name: "EQS",
        brand: "Mercedes-Benz",
        category: "Luxury",
        pricePerDay: 189,
        imageUrl: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        year: 2023,
        rating: 4.8,
        locations: ["New York", "Los Angeles", "San Francisco"],
        description: "The Mercedes-Benz EQS is the most luxurious electric car ever made, with a 56-inch Hyperscreen, 350-mile range, and whisper-quiet ride.",
        features: ["MBUX Hyperscreen", "Burmester 4D Audio", "Air Suspension", "Rear Axle Steering", "Augmented Reality Navigation", "Massage Seats"],
    },
    {
        name: "Corolla",
        brand: "Toyota",
        category: "Economy",
        pricePerDay: 39,
        imageUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.4,
        locations: ["Houston", "Chicago", "Boston"],
        description: "The Toyota Corolla is the world's best-selling car for a reason — reliable, efficient, and practical for any journey.",
        features: ["Toyota Safety Sense", "Apple CarPlay", "Lane Departure Alert", "Adaptive Cruise Control", "Rear Camera", "Wireless Charging"],
    },
    {
        name: "Elantra",
        brand: "Hyundai",
        category: "Economy",
        pricePerDay: 42,
        imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.4,
        locations: ["Houston", "Miami", "Boston"],
        description: "The Hyundai Elantra offers award-winning style, safety, and technology at an affordable price point.",
        features: ["10.25-inch Touchscreen", "Bose Audio", "SmartSense Safety", "Heated Seats", "Wireless CarPlay", "Remote Start"],
    },
    {
        name: "Forte",
        brand: "Kia",
        category: "Economy",
        pricePerDay: 38,
        imageUrl: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Petrol",
        year: 2023,
        rating: 4.3,
        locations: ["Houston", "Chicago", "Miami"],
        description: "The Kia Forte combines sporty styling with practical features and outstanding value, making it the smart choice for everyday driving.",
        features: ["8-inch Touchscreen", "Apple CarPlay", "Drive Mode Select", "Rear Camera", "Lane Keep Assist", "Forward Collision Warning"],
    },
    {
        name: "Accord",
        brand: "Honda",
        category: "Sedan",
        pricePerDay: 65,
        imageUrl: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        year: 2023,
        rating: 4.6,
        locations: ["New York", "Boston", "San Francisco"],
        description: "The Honda Accord Hybrid is a mid-size sedan that excels in every category — performance, comfort, technology, and fuel efficiency.",
        features: ["Honda Sensing", "12.3-inch Digital Cluster", "Bose Premium Audio", "Wireless CarPlay", "Remote Engine Start", "Heated Rear Seats"],
    },
];

async function seed(): Promise<void> {
    try {
        const uri = process.env.MONGODB_URI;
        if (!uri) throw new Error("MONGODB_URI is not defined");

        await mongoose.connect(uri);
        console.log("MongoDB connected for seeding");

        await Vehicle.deleteMany({});
        console.log("Existing vehicles cleared");

        await Vehicle.insertMany(vehicles);
        console.log(`${vehicles.length} vehicles seeded successfully`);

        await mongoose.disconnect();
        console.log("Seeding complete. MongoDB disconnected.");
        process.exit(0);
    } catch (error) {
        console.error("Seeding failed:", error);
        process.exit(1);
    }
}

seed();